### ISSUE TITLE
Preview 1.0.x feedback

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/T2#123]
- [x] Remove logo opacity.
- [x] Verify tab does not allow manual public key entry.
- [x] tzbtc amount entry is not taking into account scale.
- [x] tzbtc transaction row does not take into account scale.
- [x] token amount on transfer attempt should be validated against the current balance
- [x] tzip7 mint operation does not show the minted token balance or the destination account.
- [x] update sign/verify messaging.
- [ ] clicking on the sidebar button should activate it, not just clicking on the text.
- [ ] disable mickey mouse hand on token sidebar items.

**Comment by navi-arneja** [comment]
- Restore from backup should say enter 24 word seed phrase
- "Seed phrase must contain no more than 15 words" error prevents adding the full seed phrase
- When typing in the seed phrase, duplicate words don't show up in the drop-down

**Comment by navi-arneja** [comment]
- [ ] Fee rendering bug https://drive.google.com/file/d/1ifuA-lalWE41tw_0S_MoAUTFqfEOiQZv/view?usp=sharing
- [ ] Entire sign and verify tab should be clickable

**Comment by anonymoussprocket** [comment]
I think that's just fees getting updated for the current network state

**Comment by anonymoussprocket** [comment]
all pending items moved to #143
