### ISSUE TITLE
When copied & pasted seed phrases to the Restore input the number of phrases is double

### ISSUE THREAD

**Issue by szewczykkarolina** [Cryptonomic/T2#220]
When copy & paste the seed phrase to the Restore input the number is separate from the words and there is a double of phrase. When the phrase is written one by one this not happens

<img width="1111" alt="Screenshot 2020-09-08 at 15 42 29" src="https://user-images.githubusercontent.com/29228410/92484982-ab7da180-f1ea-11ea-86ad-293181a9d6fd.png">

**Comment by anonymoussprocket** [comment]
resolved in an earlier release
