### ISSUE TITLE
Add an Account -> Import Fundraiser Wallet -> 15 Word Secret Key input not render after user changes

### ISSUE THREAD

**Issue by szewczykkarolina** [Cryptonomic/T2#222]
Add an Account -> Import Fundraiser Wallet -> 15 Word Secret Key, when the user press all phrases, deletes one and adds again there will be an error. Looks like input is not checked again after every change from the user side, only after refreshing the page

**Comment by shaun-19826** [comment]
Hello, has your issue been resolved or you're still having this issue ?

**Comment by anonymoussprocket** [comment]
resolved in an earlier release
