### ISSUE TITLE
Staking Rewards

### ISSUE THREAD

**Issue by Premiere20** [Cryptonomic/T2#242]
Hello, 
Don't know where to get help. I opened the Galleon wallet in June, and delegated same day. Just checked wallet, no change in balance. Please direct me to proper place for help.

Thank you, 

John

**Comment by anonymoussprocket** [comment]
Hi John, please email Cryptonomic for support with the Galleon wallet. Reward deposits are up to the baker you've delegated to. Hopefully they have a means of contact. You can also checkout the [Harpoon](https://harpoon.arronax.io/) for baker payout details.
