### ISSUE TITLE
Beacon address not match

### ISSUE THREAD

**Issue by pascuin** [Cryptonomic/T2#289]
Great to see Beacon support in action! I've tested this with the Beacon Example dApp and found one issue.

- Beacon Example dApp: Beacon SDK v2.0.0, Galleon added in the wallet list
- Galleon 1.1.8-beta (24) on MacOS

## Steps to reproduce

1. Select "Galleon" in the Example dApp
2. Approve the permission request in Galleon
3. Trigger operation request on the Beacon Example dApp (Custom Tezos Operation)
4. Galleon shows error "Beacon address not match"

![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/9214127/103204696-3698b980-48f8-11eb-8bc4-8938b8ca1f1f.png)

**Comment by anonymoussprocket** [comment]
Should be resolved on 1.1.9b!

**Comment by anonymoussprocket** [comment]
resolved in an earlier release
