### ISSUE TITLE
Fix decimal formatting and display for tokens

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#318]
For example, a balance of 10,000 STKR will show up as 10.000,00

When trying to send 1,000 tokens the following send error occurs: Syntax error at line 1 col 91: Pair "tzABC" (Pair "tzXYZ" 1e ^ Unexpected word token: "e". Instead, I was expecting to see one of the following: A character matching /[\s]/ based on: _$ebnf$1 →...

**Comment by anonymoussprocket** [comment]
resolved in an earlier release
