### ISSUE TITLE
Unable to restore from backup

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#326]
Users are unable to restore from backup after pasting their seed phrase 1.1.17b

Steps taken
1. Create new wallet
2. Restore from backup
3. Enter seed phrase
 
The "restore" buttons stays disabled even if if the seed phrase is valid. The expected behavior is that the restore button should be enabled once a valid seed phrase is entered.

**Comment by vishakh** [comment]
Needs to be tested on a Windows VM.

**Comment by vishakh** [comment]
Could not replicate. Assuming fixed!
