### ISSUE TITLE
Update Beacon SDK to latest version

### ISSUE THREAD

**Issue by pascuin** [Cryptonomic/T2#399]
It looks like Galleon is currently using Beacon SDK 2.2.8 with the latest version being [2.3.2](https://github.com/airgap-it/beacon-sdk/tree/v2.3.2)

`    "@airgap/beacon-sdk": "2.2.8",`

We're planing on finally shutting down the Beacon Legacy node this week, while not updating should not have any negative impact on your users, many improvements have been included in the latest releases.

**Comment by anonymoussprocket** [comment]
Handled in 1.1.26
