### ISSUE TITLE
Fix bug that produces an incorrect link to operations

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#481]
When a user submits a transaction using Beacon, it produces an incorrect link to view it in Arronax. 

- [x] Please update to produce the correct operation ID. [Replace clearOperationId function] 

- [x] Replace Arronax link with a link to view it in [Tezblock](https://tezblock.io/)

- [x] Update "view on Arronax" text to say "view on block explorer" as shown below
<img width="554" alt="Screen Shot 2022-04-28 at 3 22 35 PM" src="https://user-images.githubusercontent.com/60450742/165830290-14193c43-47ac-4219-a02a-56fd8f0cc79b.png">

**Comment by vishakh** [comment]
Perhaps it makes sense to link to Tezblock instead as Arronax is not an actively funded project?

**Comment by navi-arneja** [comment]
> Perhaps it makes sense to link to Tezblock instead as Arronax is not an actively funded project?

Good point. The ticket has been updated to reflect this.
