### ISSUE TITLE
Fix NFT rendering and links 

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#482]
1. Currently, there are NFTs that don't render in the gallery view but are visible when you click on them. If we are able to render an NFT image full screen, it should be available to view in the gallery view.

2. View on objkt  should lead to the listing on objkt not ipfs

<img width="352" alt="Screen Shot 2022-04-18 at 5 30 04 PM" src="https://user-images.githubusercontent.com/60450742/163881277-daace301-6bc1-489c-baf3-48bdef8d2f58.png">

[Please ask me for a video, I'm unable to attach it to this ticket]

**Comment by vgaudis** [comment]
I have the same thing on a OneOf NFT! And the link to OneOf on the Details view does not work.
https://bafybeiayzvv5y74k47i4owbkgeklj5eysxc2j6zcgd5zomlzn56yeeo6ue.ipfs.dweb.link/

https://user-images.githubusercontent.com/84809270/163885788-98a1d0f6-25c1-495a-80cc-4f808931b1a6.mov
