### ISSUE TITLE
App crashes when selecting the liquidity baking tab while on Testnet

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#502]
When using Gallon with testnet nodes, clicking on the "Liquidity Baking" tab causes the app to crash

Tested with MacOS v 1.3.4 
Nodes: Tezos Florencenet(nautilus.cloud)

**Comment by vishakh** [comment]
We don't support Florencenet anymore.  Could you please try this again with Jakartanet?

**Comment by navi-arneja** [comment]
Tested again with Jakartanet and the same issue exists

**Comment by vishakh** [comment]
The underlying cause turned out to be that Galleon doesn't yet support testnet liquidity baking. Rather than add support to the current version, we will add it to the new iteration of Galleon under work.
