### ISSUE TITLE
Error when trying to interact with NFTs

### ISSUE THREAD

**Issue by navi-arneja** [Cryptonomic/T2#504]
When attempting to purchase, mint or cancel an offer on fxhash users see the following error:

`(permanent: proto.014-PtKathma.validate_operation.gas_quota_exceeded_init_deserialize), (temporary: proto.014-PtKathma.gas_exhausted.operation).`

To investigate:
- [ ] Replicate the issue using https://www.fxhash.xyz/

- [ ] Describe why it might be occurring & fix if needed

**Comment by vgaudis** [comment]
Same thing happening on OJKT.com when I try to purchase an NFT with Galleon I get the same error message:

(permanent: proto.014-PtKathma.validate_operation.gas_quota_exceeded_init_deserialize), (temporary: proto.014-PtKathma.gas_exhausted.operation)
